### ISSUE TITLE
Add property url on (relevant) data sources [JDBC521]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#217]
Submitted by: @mrotteveel

Add a property url on \(relevant\) data sources, which accepts a JDBC url \(including connection properties\), and parses it to relevant configuration\. 

See <https://stackoverflow.com/questions/48911266/proper-setup-of-jaybird-firebird-datasource-with-hikaricp> for an example\. For some reason this property seems to be required to exist by either Spring JPA or Hibernate, or maybe by the code used by the OP\.

For now tentatively scheduled for next bug fix releases, this may change if it turns out to be a problem with this specific code\.

**Comment by mrotteveel** [comment]
Decided not to do this.
