### ISSUE TITLE
Investigate ResultSet behavior in autocommit [JDBC209]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#258]
Submitted by: @mrotteveel

Relate to [JDBC305](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC305+in%3Atitle)
Relate to [JDBC304](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC304+in%3Atitle)

The behavior of closing ResultSets in autocommit mode might be too restrictive\. Identify current behavior in Jaybird and other drivers, and see if we can/need to change anything in this regard\.

See also the discussion "\[Firebird\-Java\] OpenOffice, Jaybird and Embedded Server " on the Firebird\-Java list\.
and <http://stackoverflow.com/questions/935511/how-can-i-avoid-resultset-is-closed-exception-in-java> \(answer by Sugar\)

**Comment by mrotteveel** [comment]
Decided not to change the current behaviour.
