### ISSUE TITLE
Attempt to retrieve actual processId [JDBC225]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#274]
Submitted by: @mrotteveel

Is duplicated by [JDBC334](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC334+in%3Atitle)
Is related to [JDBC118](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC118+in%3Atitle)

Currently Jaybird uses a System property set by the user to determine the processid to send to the server\. Extend that to use the following mechanisms \(in order\):
1\) sun\.java\.launcher\.pid, \(only Available on Oracle/Sun Java\)
2\) ManagementFactory\.getRuntimeMXBean\(\)\.getName\(\) \(should provide the PID on most or all platforms\)
3\) If all else fails: fall back to the property

**Comment by mrotteveel** [comment]
Requires Java 10 minimum to retrieve process id, because that version introduced `RuntimeMXBean.getPid()`, otherwise it has to be extracted from `RuntimeMXBean.getName()`, but there is no guarantee it actually contains the process id. This will need to wait until we no longer support Java 8.

**Comment by mrotteveel** [comment]
A better way might actually be to use `ProcessHandle.current().pid()` as that avoids a dependency on the `java.management` module, see [`ProcessHandle`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/ProcessHandle.html)
