### ISSUE TITLE
Versioning schema since v4

### ISSUE THREAD

**Issue by pzygielo** [FirebirdSQL/jaybird#30]
Versioning used since 4.0.0 is not following [Version Order Specification](https://maven.apache.org/pom.html#Version_Order_Specification).
In maven world it causes tools based on this spec to not resolve versions correctly, due to treating ".javaX" as updatable specifier - for example:

```shell
$ mvn versions:display-dependency-updates
...
[INFO] The following dependencies in Dependency Management have newer versions:
[INFO]   org.firebirdsql.jdbc:jaybird ............. 4.0.0.java8 -> 4.0.0.java11
...
```

**Comment by mrotteveel** [comment]
This is indeed a side effect of this change. This is a trade-off with the previous situation where we had artifact ids per Java version. Note that the Microsoft SQL Server JDBC driver and PostgreSQL JDBC driver use a similar naming convention.
