### ISSUE TITLE
Isolate/extract metadata ResultSet behavior [JDBC310]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#356]
Submitted by: @mrotteveel

Jira\_subtask\_inward [JDBC308](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC308+in%3Atitle)

As described in the parent issue, the current behavior of metadata ResultSets lead to some problems\. Change the existing fix so casts to VARCHAR\(31\) are no longer necessary\. The current conditional behavior for metadata ResultSet could be isolated to a separate subclass of FBResultSet, or maybe in a Strategy\.

**Comment by mrotteveel** [comment]
I'm making some changes to address this partially, and remove most of those casts. This issue to refactor metadata result sets to a separate class has been unscheduled, as there is no urgent reason to do this.

**Comment by mrotteveel** [comment]
With recent changes to how database metadata is handled, this has become less of an issue.
