### ISSUE TITLE
After rs.updateString(ColNbr) and rs.updateRow() ==> rs.getString(sameCol) is null

### ISSUE THREAD

**Issue by isfce** [FirebirdSQL/jaybird#37]
Jaybird v3 or v4 with JAVA 11 (classpath):

Simple Test with TestNG

		try(Statement q07= connexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);){
			ResultSet rs=q07.executeQuery("SELECT * FROM COUNTRY");				
			rs.absolute(5);
			String n=rs.getString(2);
			//update column
			rs.updateString(2, n+"_1");
			rs.updateRow();
			
			String r=rs.getString(2);//r is null ????
			assertEquals(r,n+"_1");
			
		} catch (SQLException e) {
			fail();
		}

**Comment by mrotteveel** [comment]
The workaround is to add a `rs.refreshRow()` after `rs.updateRow()`.

**Comment by mrotteveel** [comment]
This issue is not reproducible with Jaybird 3. What is the type of the field you're using?

**Comment by mrotteveel** [comment]
Fix will be included with Jaybird 4.0.4 and Jaybird 5. Thanks for reporting.

I will close this issue now, but if you are able to reproduce it with Jaybird 3.0.11, then I'd really like a complete reproduction script, including database setup.

**Comment by isfce** [comment]
Sorry, It's working fine with Jaybird 3.0.11!

**Comment by mrotteveel** [comment]
> Sorry, It's working fine with Jaybird 3.0.11!

Thanks for confirming. I'm not yet sure when I'm going to release Jaybird 4.0.4, but if you'd like a snapshot build, let me know.
