### ISSUE TITLE
Refactor type info lookup and conversion between Firebird and JDBC type information [JDBC324]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#370]
Submitted by: @mrotteveel

Decisions on type information happens in to many places \(eg in FBDatabaseMetaData, FBResultSetMetaData, FBParameterMetaData, FBField\)\. This should be factored out to a single repository of information for types\.

**Comment by mrotteveel** [comment]
This has already been done over the course of Jaybird 3, 4 and 5.
