### ISSUE TITLE
getClientInfo returning Properties object never returns anything [JDBC365]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#407]
Submitted by: @mrotteveel

The method public Properties getClientInfo\(\) in FBConnection never returns anything, because it uses a set of keynames \(clientInfoPropNames\) that is never populated\.

**Comment by mrotteveel** [comment]
See [jdp-2023-11: New design client info properties](https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2023-11-new-design-client-info-properties.adoc)
