### ISSUE TITLE
getClientInfo doesn't return system context information [JDBC366]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#408]
Submitted by: @mrotteveel

getClientInfo doesn't return system context information, however the apidoc suggests it should also report connection and system level information

**Comment by mrotteveel** [comment]
Re-reading this, I'm not so sure if system context information should be reported, maybe with the exception of - by default, if not explicitly set - mapping `ApplicationName` to (SYSTEM, CLIENT_PROCESS). The `ClientUser` and `ClientHostname` properties seem to be intended for the application itself to map *its* users (e.g. users of a Web API) and their location to a database, not the (effective) database user and host.

On the other hand, allowing retrieval (and mapping them for example to `<property-name>@SYSTEM`) would be a simple measure to give access to this information. Similarly, reporting USER_TRANSACTION info as `<property-name>@USER_TRANSACTION`, and allowing set that way (and mapping sets with `<property-name>@USER_SESSION` the same as sets with `<property-name>`)

**Comment by mrotteveel** [comment]
Will handle this further as part of #407
