### ISSUE TITLE
Improve performance of  PreparedStatement executeBatch() in Jaybird [JDBC377]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#419]
Submitted by: @pavel-zotov

Attachments:
[trace-jdbc-running-statements.zip](https://github.com/FirebirdSQL/jira-attachments/raw/main/JDBC/JDBC-377/12644_trace-jdbc-running-statements.zip)

I've decided to compare performance of batch inserts of 50'000 rows into trivial table: CUSTOMER\(id int primary key, name varchar\(20\)\) when use Jaybird and PSQL execute statement\.

PSQL:
=====

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- begin of file 'ins\_prepared\.sql' \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
set term ^;
execute block as begin
  execute statement 'create sequence g'; when any do begin end
end
^ set term ;^
commit;

alter sequence g restart with 0;
commit;

delete from customer;
commit;

select 1 from customer; \-\- collect garbage
commit;

out nul;
select rdb$set\_context\('USER\_SESSION','T0', cast\(current\_timestamp as varchar\(24\)\) \) from rdb$database;
out;

set term ^;
execute block as
  declare i int = 0;
  declare n int = 50000;
  declare s varchar\(50\) = 'insert into customer values\( :x, :y\)';
begin
  rdb$set\_context\('USER\_SESSION','BATCH', n \);
  while \(i < n\) do 
  begin
    execute statement \( s \) \( x := i, y := 'cust#&#x2060;'\|\|i \);
    i = i \+ 1;
  end
end
^ set term ;^
commit;

out nul;
select rdb$set\_context\('USER\_SESSION','T1', cast\(current\_timestamp as varchar\(24\)\) \) from rdb$database;
out;

select 'BATCH=' \|\| rdb$get\_context\('USER\_SESSION','BATCH'\) \|\| ', elapsed time of loop\+commit: '
        \|\| datediff\( millisecond 
                     from cast\( rdb$get\_context\('USER\_SESSION','T0'\) as timestamp\)
                     to   cast\( rdb$get\_context\('USER\_SESSION','T1'\) as timestamp\)
                   \)
from rdb$database;
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- end of file 'ins\_prepared\.sql' \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Test command:

isql localhost/3050:t0 \-n \-i ins\_prepared\.sql \-pag 0

TestPreparedDML\.java \(use jaybird\-full\-2\.2\.5\.jar\)
==================

import java\.sql\.\*;
import org\.firebirdsql\.jdbc\.\*;
import org\.firebirdsql\.gds\.\*;
public class TestPreparedDML \{

  private static int BATCH\_SIZE = 50000;

  public static void main\(String\[\] args\) \{
    new TestPreparedDML\(\)\.run\(\);
  \}

  private void run\(\) \{
      FirebirdConnection c = null;
      PreparedStatement p = null;
      Statement s = null;
      try \{
        c = attach2fb\(\);
        c\.setAutoCommit\(false\);
        s = c\.createStatement\(\);
        s\.executeUpdate\("delete from customer"\);
        c\.commit\(\);

        p = c\.prepareStatement\("insert into customer\(id, name\) values\(?, ?\)"\);

        System\.out\.println\("Start loop with addBatch\(\)\.\.\."\);
        long t0 = System\.currentTimeMillis\(\);
        for\( int i=0; i < BATCH\_SIZE; i\+\+ \) \{
            p\.setInt\(1, i\);
            p\.setString\(2, "cust #&#x2060;"\+i\);
            p\.addBatch\(\);
        \}
        System\.out\.println\("Start executeBatch\(\)\.\.\."\);
        long t1 = System\.currentTimeMillis\(\);
        p\.executeBatch\(\);
        c\.commit\(\);
        long t2 = System\.currentTimeMillis\(\);
        System\.out\.println\("BATCH\_SIZE="\+BATCH\_SIZE\+", elapsed time: loop\+addBatch: "\+\(t1\-t0\)\+", executeBatch\+commit: "\+\(t2\-t1\)\);
        p\.close\(\);
        c\.close\(\);
      \} catch \(SQLException e\) \{
        e\.printStackTrace\(\);
      \}
  \}

  private static FirebirdConnection attach2fb\(\) \{
    FirebirdConnection con = null;
    TransactionParameterBuffer tpb = null;
    int til = Connection\.TRANSACTION\_READ\_COMMITTED; // to start RC tx
    //int til = Connection\.TRANSACTION\_REPEATABLE\_READ; // to start SNAPSHOT tx

    String url = "jdbc:firebirdsql://localhost:3050/t0";
    String usr = "sysdba";
    String psw = "masterke";

    try \{
       // <http://www.javadocexamples.com/java_source/org/firebirdsql/jdbc/TestFBConnection.java.html>
       con = \(FirebirdConnection\)java\.sql\.DriverManager\.getConnection\(url, usr, psw\);
       tpb = con\.getTransactionParameters\(til\);
       tpb\.removeArgument\(TransactionParameterBuffer\.WAIT\);
       tpb\.addArgument\(TransactionParameterBuffer\.NOWAIT\);
       con\.setTransactionParameters\(til, tpb\);
       con\.setTransactionIsolation\(til\);
    \}
    catch \(Exception x\) \{
      x\.printStackTrace\(\);
    \}
    return con;
  \}
\}

Then I've run seven times each test\.

Results of  PSQL:
==============
BATCH=50000, elapsed time of loop\+commit: 2750
BATCH=50000, elapsed time of loop\+commit: 2781
BATCH=50000, elapsed time of loop\+commit: 2812
BATCH=50000, elapsed time of loop\+commit: 3375
BATCH=50000, elapsed time of loop\+commit: 3343
BATCH=50000, elapsed time of loop\+commit: 2797
BATCH=50000, elapsed time of loop\+commit: 2828

Results of JDBC:
=============
BATCH\_SIZE=50000, elapsed time: loop\+addBatch: 172, executeBatch\+commit: 14843
BATCH\_SIZE=50000, elapsed time: loop\+addBatch: 188, executeBatch\+commit: 14312
BATCH\_SIZE=50000, elapsed time: loop\+addBatch: 203, executeBatch\+commit: 14953
BATCH\_SIZE=50000, elapsed time: loop\+addBatch: 203, executeBatch\+commit: 14609
BATCH\_SIZE=50000, elapsed time: loop\+addBatch: 203, executeBatch\+commit: 14578
BATCH\_SIZE=50000, elapsed time: loop\+addBatch: 203, executeBatch\+commit: 14500
BATCH\_SIZE=50000, elapsed time: loop\+addBatch: 219, executeBatch\+commit: 14547

When I've reduced number of batches in JDBC test down to 5 and run Firebird trace, I could not understand the reason of bad performance: there is only \*single\* PREPARE\_STATEMENT record and also \*single\*  COMMIT\_TRANSACTION\. Statistics for table CUSTOMER is the same as for PSQL\.

Is it possible to improve JDBC performance when making batch DML ?

PS\. Trace sample for batch\_size = 5  when run java class please see in attach\.

**Comment by mrotteveel** [comment]
The performance difference between the PSQL example and using `addBatch()` + `executeBatch()` is that batch execution in its current form performs an execute (one roundtrip), and retrieves the update counts (one more roundtrip) per set of parameters. As long as Jaybird doesn't support Firebird 4 batch protocol, it is better to execute the statements individually with `execute()` (not `executeUpdate`!) with auto-commit mode disabled.
