### ISSUE TITLE
Create correct SPB version for service parameter and request buffers [JDBC422]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#463]
Submitted by: @mrotteveel

The AbstractFbService implement currently always creates an SPB version 2 for the non\-attach service parameter buffer and service request buffer\. The code needs to be changed to create the SPB version supported by the Firebird version\.

When changing this, also look at the streaming backup / restore implementation to support larger buffers\.

**Comment by mrotteveel** [comment]
SPB version 3 only applies to the attach parameter buffer, and not to others usages. Still looking at if there are some buffer usages that could be bigger.

**Comment by mrotteveel** [comment]
Buffer usage can't be bigger either. Removed various TODOs
