### ISSUE TITLE
Refactor handling of metadata statements/transactions [JDBC465]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#504]
Submitted by: @mrotteveel

Is related to [JDBC464](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC464+in%3Atitle)
Is related to [JDBC470](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC470+in%3Atitle)

As shown in [JDBC464](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC464+in%3Atitle) metadata statement handling has some issues\. Currently it piggybacks on the active transaction, but maybe it should use its own \(read only\) transaction instead\.

**Comment by mrotteveel** [comment]
With the changes in behaviour of `READ COMMITTED` in Firebird 4.0, using a separate read-only transaction handle for database metadata no longer provides a lot of benefits, but does introduce more overhead (e.g. inhibiting GC), so this is no longer a viable solution.
