### ISSUE TITLE
Firebird 4 support [JDBC466]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#505]
Submitted by: @mrotteveel

Jira\_subtask\_outward [JDBC467](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC467+in%3Atitle)
Jira\_subtask\_outward [JDBC468](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC468+in%3Atitle)
Jira\_subtask\_outward [JDBC506](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC506+in%3Atitle)
Jira\_subtask\_outward [JDBC516](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC516+in%3Atitle)
Jira\_subtask\_outward [JDBC540](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC540+in%3Atitle)
Jira\_subtask\_outward [JDBC564](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC564+in%3Atitle)
Jira\_subtask\_outward [JDBC570](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC570+in%3Atitle)
Jira\_subtask\_outward [JDBC583](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC583+in%3Atitle)
Jira\_subtask\_outward [JDBC591](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC591+in%3Atitle)
Jira\_subtask\_outward [JDBC595](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC595+in%3Atitle)
Jira\_subtask\_outward [JDBC596](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC596+in%3Atitle)
Jira\_subtask\_outward [JDBC624](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC624+in%3Atitle)

Identify the changes and new features in Firebird 4 and add support \(through subtasks\)\.

Tentatively scheduled for Jaybird 4\. Some things may move to 3\.0, otherwise might be delayed further\.

**Comment by mrotteveel** [comment]
This was a parent issue in Jira, no longer relevant, so closing it.
