### ISSUE TITLE
Documentation of setTpbMapping incorrect [JDBC522]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#557]
Submitted by: @mrotteveel

The documentation of setTpbMapping incorrectly states "The path begins with the protocol specification followed by the path to the resource\. A special protocol "res:" should be used to specify resource in the classpath\."

In reality the "res:" protocol is not supported, and instead of a path to the resource, it is a bundle name\.

1\. Revise documentation
2\. Consider implementing the 'res:' protocol to actually accept a classpath resource\.

**Comment by mrotteveel** [comment]
Revised documentation, left remainder as is.
