### ISSUE TITLE
Produce information for IntelliJ IDEA / Datagrip [JDBC525]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/jaybird#559]
Submitted by: @mrotteveel

Votes: 9

To get Jetbrains to add support for Firebird, we need to provide information

\* SQL grammar
\* Documentation for built\-in functions
\* Database catalog description
\* Catalog introspection queries
\* JDBC Driver information
\* Test instance and data
\* Licensing/permission

See <https://youtrack.jetbrains.com/issue/DBE-3650> and <https://www.jetbrains.com/datagrip/new_dbms/>

**Comment by Dynozavrus** [comment]
@JetBrains... 12 years ago...  🥇
