### ISSUE TITLE
Investigate options to package Firebird embedded in a 'self-deploying' jar. [JDBC533]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#566]
Submitted by: @mrotteveel

Firebird Embedded is rather complicated to deploy correctly\. It would be helpful if it is possible to deploy as a single jar, which is then extracted appropriately on first use \(or maybe explicit init\)\. The MongoDB Embedded library does something similar, see <https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo>

Also notify <https://github.com/dbeaver/dbeaver/issues/3397> when this is available\.

Commits: FirebirdSQL/jaybird@fddb4ae716ea3fdd29ddbabcd9a2b517458a70c5 FirebirdSQL/jaybird@9028f2ce8d569201bf3667ec386c52cc2e447af7

**Comment by mrotteveel** [comment]
For the Linux build, ensure that libtommath.so.0 is included

**Comment by mrotteveel** [comment]
Probably needs a custom build that includes libtommath and libtomcrypt.

**Comment by mrotteveel** [comment]
I marked the JDP and feature as experimental for Jaybird 5.

**Comment by mrotteveel** [comment]
Experimental variant for Windows (x86-64): https://github.com/mrotteveel/jaybird-embedded-win32-x86-64
