### ISSUE TITLE
Add permission check for RC4 encryption with 160 bits key and otherwise default to wireCrypt=DISABLED instead of ENABLED [JDBC546]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#579]
Submitted by: @mrotteveel

Is related to [JDBC543](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC543+in%3Atitle)

See [JDBC543](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC543+in%3Atitle)\. Investigate if it is possible to check if we can use RC4/ARCFOUR with 160 bits key and if not default to wireCrypt DISABLED \(eg if the limited cryptographic jurisdiction policy is used\)\.

**Comment by mrotteveel** [comment]
Decided not to do this
