### ISSUE TITLE
Firebird 4: Add Firebird 4 reserved words to FirebirdVersionMetaData  [JDBC564]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#597]
Submitted by: @mrotteveel

Jira\_subtask\_inward [JDBC466](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC466+in%3Atitle)

Commits: FirebirdSQL/jaybird@5dd183aa1a004e0caa9b42e2f960a12c25257392 FirebirdSQL/jaybird@301b6b1c1a2ee6a09e951efd7d03239495f12a73 FirebirdSQL/jaybird@b72565e68de0babeacd14dc167a701ae4993f866

**Comment by mrotteveel** [comment]
Updated with 4.0.0.2496 reserved words
