### ISSUE TITLE
Improve cursor close handling [JDBC573]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#604]
Submitted by: @mrotteveel

Is related to [JDBC531](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC531+in%3Atitle)
Is related to [JDBC571](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC571+in%3Atitle)

In [JDBC571](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC571+in%3Atitle) we added some stopgap measures for CURSOR\_OPEN state affecting reuse\. We need to investigate if there is a better, more general solution possible\. Part of the problem is that the driver relies \(relied\) on result set creation to properly close the statement cursor, while some code paths don't create a result set \(or fail to create one, as addressed in [JDBC571](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC571+in%3Atitle)\)\.

For example another codepath that causes this problem \(which is corrected by the stopgap measure \`ensureClosedCursor\`\) is executing a select with \`Statement\.execute\(\.\.\)\`, but never actually retrieving the result set with \`getResultSet\(\)\`\. Before the stopgap measure, this would leave the statement in CURSOR\_OPEN state, disallowing reuse\.

**Comment by mrotteveel** [comment]
Promoted the stopgap to the definitive solution, removing the debug logging.
