### ISSUE TITLE
Current statement has no data to return. [JDBC605]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#636]
Submitted by: Attila Molnár (e_pluribus_unum)

Hi Mark\!

The "test" proc is selectable, but executed via EXECUTE PROCEDRURE/CallableStatement\. Reading out parameter cause "Current statement has no data to return\." exception\. I think in this case null value should be returned 
The resultset is empty beacuse of no suspend is actually called in "test", but it was not executed via SELECT\.

try\(Connection conn = ds\.getConnection\(\)\) \{
	String create = "create or alter procedure test\\n" \+
		"returns \(msg varchar\(1000\)\)\\n" \+
		"as\\n" \+
		"begin\\n" \+
		"  msg = '';\\n" \+
		"  if \(msg <\> ''\) then suspend;\\n" \+
		"end";
	conn\.setAutoCommit\(false\);
	conn\.setReadOnly\(false\);
	conn\.createStatement\(\)\.execute\(create\);
	conn\.commit\(\);
	CallableStatement cs = conn\.prepareCall\("EXECUTE PROCEDURE test \(?\)"\);
	cs\.registerOutParameter\(1, java\.sql\.Types\.VARCHAR\);
	cs\.execute\(\);
	String msg = cs\.getString\("MSG"\);//Current statement has no data to return\.
\}

**Comment by mrotteveel** [comment]
I added a test asserting the existing behaviour.

**Comment by mrotteveel** [comment]
I'm going to leave the existing behaviour as is.
