### ISSUE TITLE
Add support for Chacha wire encryption plugin [JDBC613]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#644]
Submitted by: @mrotteveel

Firebird 4 adds support for the chacha wire encryption plugin\. However, its implementation comes with the caveat that it doesn't implement the RFC\-8439 variant of Chacha, but instead Firebird supports 128 bit and 256 bit keys, and given SRP produces 160 bit keys, will use the first 128 bits of that key\. Java provides Chacha \(RFC\-8439 variant, requiring 256 bit keys\) support since Java 11, so to support it in an earlier Java versions would require implementing a custom cipher \(for example based on the BouncyCastle implementation\)\.

Implementing a custom cipher would allow us to support both the 128 bit and 256 bit variant, but comes with the obvious overhead of having to implement crypto code in Jaybird\.

**Comment by mrotteveel** [comment]
Decided to only implement this in Jaybird 5, and only for Java 11 and higher.
