### ISSUE TITLE
For FBStatement, unprepare statement after statement completion [JDBC637]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/jaybird#667]
Submitted by: @mrotteveel

Internally, FBStatement also prepares the statement, and keeps it prepared until the next statement is executed\. It would probably be a good idea to automatically unprepare \(free with DSQL\_unprepare\) the statement on statement completion to prevent retention of existence locks\.

Commits: FirebirdSQL/jaybird@517b0550a01454ebc6d9887f7dd7e9cf99893311

**Comment by mrotteveel** [comment]
The complications with the lifetime requirements has made may decide not to implement this.
