### ISSUE TITLE
version error jaybird-full-4.0.5.java8.jar

### ISSUE THREAD

**Issue by Hugolarson** [FirebirdSQL/jaybird#688]
.getMetaData().getDriverVersion() -> "4.0.4".
Should be "4.0.5"

**Comment by mrotteveel** [comment]
I haven't tried to reproduce it yet, but the org/firebirdsql/jaybird/version.properties of the archive reports 4.0.5, and the version information is (or: should be) read from this file. Are you sure you also haven't a Jaybird 4.0.4 on your classpath?

**Comment by Hugolarson** [comment]
Sorry it was an Eclipse issue.

closing.

Hugo
