### ISSUE TITLE
Support for FB4 Nbackup RDB$BACKUP_HISTORY cleanup

### ISSUE THREAD

**Issue by Hugolarson** [FirebirdSQL/jaybird#706]
https://github.com/FirebirdSQL/firebird/issues/7186

**Comment by mrotteveel** [comment]
Scheduling for Jaybird 5 is tentative.

**Comment by Hugolarson** [comment]
Hi,
What about Jaybird 4?

**Comment by mrotteveel** [comment]
I'll decide that if and when I implemented it for Jaybird 5.

**Comment by mrotteveel** [comment]
Implemented for Jaybird 5 and 4.0.7
