### ISSUE TITLE
Generate error messages and SQLstate from Firebird 5.0

### ISSUE THREAD

**Issue by mrotteveel** [FirebirdSQL/jaybird#707]
Previously, the Firebird builds produced a MSG.FDB which contained error information, which is used by the `MessageDump` utility to generate error message and sqlstate files. In Firebird 5.0, this was changed, and the build no longer produces a queryable database. Instead, we need to parse the information from from include/firebird/impl/msg.

**Comment by vasiliy-yashkov** [comment]
Hi @mrotteveel! I recently wrote a program to generate property files containing error codes and error messages from Firebird 5. Written in c++. If you are interested, you can have a look at it - https://github.com/vasiliy-yashkov/message_dump

**Comment by mrotteveel** [comment]
Update messages itself closer to release of Jaybird 5.
