### ISSUE TITLE
Get execution statistics

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/jaybird#716]
Hi!

With IBX using TIBDatabaseInfo you can get insert/update/delete/read count.
It would be great if I could get the same statistics in structured objects (ExecStat[]) with a simple method call.

eg.:
ExecStat
- tableName
- insCnt
- updCnt
- delCnt
- seqReadCnt
- idxReadCnt

Thank you!

**Comment by mrotteveel** [comment]
NOTE: Scheduling for Jaybird 5 is tentative, and may change.
