### ISSUE TITLE
AsynchronousChannel connection is too fast for firebird

### ISSUE THREAD

**Issue by boerniee** [FirebirdSQL/jaybird#721]
Hello,

i'm using Spring boot with the jaybird driver to create a FBEventManager and subscribe to firebird events.
The driver is connecting successfully through the default port (3050) to the firebird and gets the response which port is used for the AsynchronousChannel to connect. While connecting this random port, the driver is occuring a connection refused every time. While testing, researching and debugging this I found out, that the firebird takes roughly 1200ms to open the socket at the random port. I have build the jaybird connector with a sleep for 2500ms before the connect in the V10AsynchronousChannel and it is working every time.
I am running the Firebird database as container with networking_mode host, so all of the random ports are reachable.
It also happens if I set the RemoteAuxPort in the firebird config manually.

Has this ever happened to anyone else? Am I doing something wrong or is there a workaround for this?

Jaybird Version: 4.0.8.java11
Spring Boot Version: 2.7.5
JDK 19
Firebird version: 2.5.7-ss (docker container)

Thank you!

**Comment by mrotteveel** [comment]
Please use [firebird-java](https://groups.google.com/g/firebird-java) for support questions.

**Comment by mrotteveel** [comment]
In any case, I'm not aware of any such delays. I do notice that you aren't using the latest Firebird 2.5. I suggest trying with 2.5.9, and trying directly to excluded the possibility that Docker is slow in exposing the port.

**Comment by AlexPeshkoff** [comment]
Add 2cc - branch 2.5 is not supported for a long time, and it's bad idea to use it.
