### ISSUE TITLE
Replace fix-version labels with milestones

### ISSUE THREAD

**Issue by mrotteveel** [FirebirdSQL/jaybird#753]
Jaybird currently uses labels with "fix-version: Jaybird \<version>" to record target versions. It makes sense to switch to using milestones. Initially, this will only be done for currently unreleased versions (5.0.3, 4.0.10 and 6), where we will replace the label with an equivalent milestone, and delete the label.

Doing this for already released versions might not make much sense, though it might reduce the clutter of labels, but will also break links in old release notes, so for the time being, we'll leave those alone (we may revisit this in the future).

**Comment by asfernandes** [comment]
Is multi-milestone being supported?
Or how can you will mark a issue as fixed in two different major versions correctly?

**Comment by mrotteveel** [comment]
> Is multi-milestone being supported? Or how can you will mark a issue as fixed in two different major versions correctly?

Ugh, I missed that. Luckily only one issue was affected, #734... I guess I'll solve that by using a separate issue to track backports.

**Comment by mrotteveel** [comment]
See also https://github.com/orgs/community/discussions/4566
