### ISSUE TITLE
Add extra explanation to "connection rejected by remote interface" (isc_connect_reject) to avoid support questions

### ISSUE THREAD

**Issue by mrotteveel** [FirebirdSQL/jaybird#779]
Now that wire protocols 12 and older are disabled by default (#733), it is more likely users will received `isc_connect_reject` (i.e. when connecting to Firebird 2.5 and older). To avoid bug reports/support questions, we need to add an extra explanation to this exception message and/or replace it with a Jaybird specific exception message (e.g. explaining this common case, and maybe link to the FAQ for more info).

**Comment by AlexPeshkoff** [comment]
Is isc_connect_reject raised inside jaybird?
I ask cause this is client-only error code in FB, it never comes from the server (may be except Execute Statement On External). And there may be other reazons except incompatible protocol - first of all non-fb listener on 3050.

**Comment by mrotteveel** [comment]
Yes, it is raised by Jaybird when `op_reject` is received, just like the fbclient does (IIRC). I know there are other reasons (I have documented a number of them in the [Jaybird FAQ](https://www.firebirdsql.org/file/documentation/drivers_documentation/java/faq.html#connection-rejected-by-remote-interface-335544421)), but now that Jaybird no longer tries protocol 10, 11 and 12 by default, I expect its frequency to increase for people stuck on older versions.

**Comment by mrotteveel** [comment]
Turns out, I already added a message in #733. I'll leave this ticket open for now to evaluate if it is "good enough".
