### ISSUE TITLE
Problem connecting with embedded "unsupported on-disk structure"

### ISSUE THREAD

**Issue by andyrozman** [FirebirdSQL/jaybird#790]
Hi !
So I followed instruction and I wanted to access my FDB file (on system that doesn't have Firebird - Linux)... This didn't work since I needed FbClient.dll. I then installed FB 5, and this started working... but then I got different problem:

unsupported on-disk structure for file XYZ.FDB; found 11.2, support 13.1 [SQLState:HY000, ISC error code:335544379].

I though that latest jdbc 5.0.4 supports all versions down to 2.5 (and it seems that my file is 2.5)? 

Kind regards,
Andy

**Comment by mrotteveel** [comment]
The error means that you're trying to open a Firebird 2.5 database with a Firebird 5.0 database engine. Although Jaybird supports *connecting* to Firebird 2.5 and higher, it doesn't mean it will magically allow you to open database not supported by the version of the database engine you use.

Firebird 5.0 can only open ODS 13.1 (Firebird 5.0) and ODS 13.0 (Firebird 4.0) databases. If you want to open an ODS 11.2 (Firebird 2.5 database), you'll need to use a Firebird 2.5 server or embedded library, or you need to back it up under Firebird 2.5 and restore it under Firebird 5.0 to upgrade the database to ODS 13.1. Note that database files created under Linux cannot (or not always) be opened under Windows.

**Comment by mrotteveel** [comment]
As an aside, for questions like this, I prefer that you use the [firebird-java Google Group](https://groups.google.com/g/firebird-java)
