### ISSUE TITLE
FirebirdConnection.setTransactionParameters(TransactionParameterBuffer tpb) and ConnectionPool Behavior

### ISSUE THREAD

**Issue by r1gm** [FirebirdSQL/jaybird#804]
Hi !
I set TransactionParameterBuffer to setTransactionParameter,  it's just run for one next transaction or all next transaction ?

If it run for all next transaction what i can do to reset the TransactionParameter before returning it to connection pool ?

Best Regards,
Erwan T

**Comment by r1gm** [comment]
Ok, thank you

**Comment by mrotteveel** [comment]
That said, your question is answered by the Javadoc of the method: [`setTransactionParameters​([TransactionParameterBuffer tpb)`](https://www.firebirdsql.org/file/documentation/drivers_documentation/java/5.0.x/docs/org/firebirdsql/jdbc/FirebirdConnection.html#setTransactionParameters(org.firebirdsql.gds.TransactionParameterBuffer)):

> This method does not change the TPB mapping, but replaces the mapping for the current transaction isolation until `Connection.setTransactionIsolation(int)` is called.

In other words, it will keep using the the specified TPB until `setTransactionIsolation(int)` is called, which hopefully your connection pool does to reset it back.
