### ISSUE TITLE
ResultSet.isBeforeFirst returns true if result set is empty

### ISSUE THREAD

**Issue by gabrieleciech** [FirebirdSQL/jaybird#807]
I have recently upgraded my driver from jaybird 4.0.9 to 5.0.4 and I found a different behaviour for the ResultSet.isBeforeFirst method call when the result set is empty.

In version 4.0.9 the method correctly returns `false` if the query has no rows in the result set, instead in version 5.0.4 it returns `true`. In this way we no longer have the possibility of understanding whether a result set is empty or not.

It seems that this change was made while developing support for server-side scrolling in #693, by changing the initialization value of the variable [isBeforeFirst in FbStatementFetcher](https://github.com/FirebirdSQL/jaybird/blame/321a1b8401a200c6f9ba3e2fd5cd57871d5da8d0/src/main/org/firebirdsql/jdbc/FBStatementFetcher.java#L69)

As a test query you can use:
```sql
SELECT 1 as myvar 
FROM rdb$database 
WHERE 1=0
```

and you get a different result executing the following code by changing the driver
```java
var conn = DriverManager.getConnection(url, user, pass);
var stmt = conn.createStatement();
var query = "SELECT 1 as myvar FROM rdb$database WHERE 1=0"

ResultSet rs = stmt.executeQuery(strSQL);
if(!rs.isBeforeFirst()) {
    System.out.println("Result set is empty");
} else {
    System.out.println("Result set with records");
}
```

**Comment by mrotteveel** [comment]
Thanks for reporting. I'll need to double check *why* I changed this. I guess I did it for consistency with the scrollable fetch, but the JDBC specification indeed says it should report `false` when the result set is empty.

**Comment by mrotteveel** [comment]
To be front-ported to Jaybird 6 as well.

**Comment by mrotteveel** [comment]
The value of `isAfterLast()` also incorrectly reported `true` for an empty result set after calling `next()`

**Comment by mrotteveel** [comment]
Behaviour in Jaybird 4 was inconsistent and depended on the result set type and concurrency.
