### ISSUE TITLE
Unable to Connect to Firebird using Jaybird JDBC with SOCKS5 Proxy: Exception in thread "main" java.sql.SQLNonTransientConnectionException: Unable to complete network request to host "localhost". [SQLState:08006, ISC error code:335544721]

### ISSUE THREAD

**Issue by qijinkui** [FirebirdSQL/jaybird#826]
I am encountering an issue when trying to connect to a Firebird database using the Jaybird JDBC driver with a SOCKS5 proxy. The connection works fine when connecting directly to the database without using the proxy, but when I try to use the SOCKS5 proxy, I receive the following error: 
```none
Exception in thread "main" java.sql.SQLNonTransientConnectionException: Unable to complete network request to host "localhost". [SQLState:08006, ISC error code:335544721]
	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$5.createSQLException(FbExceptionBuilder.java:677)
	at org.firebirdsql.gds.ng.FbExceptionBuilder$ExceptionInformation.toSQLException(FbExceptionBuilder.java:571)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toSQLException(FbExceptionBuilder.java:309)
	at org.firebirdsql.gds.ng.wire.WireConnection.socketConnect(WireConnection.java:298)

Caused by: java.net.SocketException: SOCKS: Connection refused
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:564)
	at java.net.Socket.connect(Socket.java:606)
	at org.firebirdsql.gds.ng.wire.WireConnection.socketConnect(WireConnection.java:288)
```

Steps to Reproduce:

- Jaybird Version: I am using Jaybird 5.0.6 for Java 8.
- Firebird Version: I am connecting to Firebird 2.5.6.
- SOCKS5 Proxy: I am running a local SOCKS5 proxy via Docker from the following image:
  Proxy Image: [xkuma/socks5](https://hub.docker.com/r/xkuma/socks5)
-  Custom Code in Jaybird: I have extended the WireConnection.java class to support SOCKS5 proxy connections. Specifically, I modified the socketConnect method to use a proxy if specified. Below is the relevant code I added to create a socket with the SOCKS5 proxy:
    ```java
    protected Socket createSocket() {
        // Check if a proxy server is specified
        String proxyServerName = dbAttachInfo.getProxyServerName();
        if (proxyServerName == null || proxyServerName.isEmpty()) {
            return new Socket();  // No proxy, create a regular socket
        }

        // Use SOCKS proxy
        int proxyPortNumber = dbAttachInfo.getProxyPortNumber();
        return new Socket(new Proxy(Proxy.Type.SOCKS, new InetSocketAddress(proxyServerName, proxyPortNumber)));
   }
   ```

**Comment by mrotteveel** [comment]
I'm not familiar with SOCKS, but to me the _"java.net.SocketException: SOCKS: Connection refused"_ suggests that it is the SOCKS proxy that cannot connect to the Firebird server. 

You should not use localhost, as that will refer to the Docker container with the SOCKS proxy, not to your machine running Firebird.

As an aside, is there a particular reason you're not using the `socksProxyHost` and `socksProxyPort` system properties (see [Java Networking and Proxies](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html))?

**Comment by qijinkui** [comment]
Thank you for your feedback! Here are my responses to the points you raised:

Regarding the use of socksProxyHost and socksProxyPort system properties:
    1.The main reason I am not using socksProxyHost and socksProxyPort system properties is that my use case involves distributed processing with Spark. The Spark jobs are running in a distributed environment where multiple nodes may need to connect to different databases, each potentially requiring different proxy settings.
    2.Using system properties for proxy settings would make it challenging to handle these varying proxy configurations in a scalable and flexible manner, especially when the Spark jobs are executed concurrently across many nodes.
    3.By extending the WireConnection class and programmatically creating a socket with proxy support, I can dynamically control the proxy settings for each database connection without being constrained by global system properties. This provides more fine-grained control, especially in a distributed environment where each database may have its own set of proxy rules.

**Comment by qijinkui** [comment]
Thank you for your helpful suggestion! I realize now that I made the mistake of using localhost, which caused the SOCKS proxy to refer to the Docker container rather than the host machine running Firebird. I will update the connection to use the actual IP address of the host machine, as you recommended. Thanks again for your assistance!

**Comment by mrotteveel** [comment]
You're welcome

I'm considering supporting configuring a custom `SocketFactory` in the connection string, which will probably remove the need for you to fork Jaybird and change its code.

**Comment by qijinkui** [comment]
Thanks Thank you very much.
