### ISSUE TITLE
Add support for custom SocketFactory in connection string and data sources

### ISSUE THREAD

**Issue by mrotteveel** [FirebirdSQL/jaybird#828]
Add support for configuring a custom `SocketFactory` in connection string and data sources. This will allow people to configure custom sockets (e.g. for a SOCKS proxy without relying on global configuration, see #826).

**Comment by qijinkui** [comment]
I would like to extend the functionality to support proxy authentication as well. Thank you very much!

Authenticator.setDefault(new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                String proxyUser = dbAttachInfo.getProxyUser();
                String proxyPwd = dbAttachInfo.getProxyPwd();
                return new PasswordAuthentication(proxyUser, proxyPwd.toCharArray());
            }
        });

**Comment by mrotteveel** [comment]
That would be a problem that the custom [`SocketFactory`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/javax/net/SocketFactory.html) would need to solve. I'll try to think of a way that allows for some context information to be passed.

**Comment by mrotteveel** [comment]
Proposal: [jdp-2024-09: Custom socket factory for pure Java connections](https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2024-09-custom-socket-factory-for-pure-java-connections.adoc)
