### ISSUE TITLE
Saving tomcat session data error(Malformed string)

### ISSUE THREAD

**Issue by r1gm** [FirebirdSQL/jaybird#829]
Dec 07, 2024 11:57:34 AM org.apache.catalina.session.DataSourceStore save
SEVERE: SQL Error [java.sql.SQLException: Dynamic SQL Error; SQL error code = -303; Malformed string [SQLState:22000, ISC error code:335544849]]

it's saving session data using 
preparedSaveSql.setBinaryStream(3, in, size);

my database column using 
SESSION_DATA BLOB SUB_TYPE 1

am i using wrong column type ?

Jaybird Version 
5.0.5.java11

FirebirdSql Version
5.0.1

**Comment by mrotteveel** [comment]
Yes, you're probably using the wrong column type. `BLOB SUB_TYPE 1` is also known as `BLOB SUB_TYPE TEXT`, and is intended for textual data, not binary data. It's basically what some other database systems call a CLOB. For binary data, you need to use `BLOB` (a.k.a `BLOB SUB_TYPE 0` a.k.a. `BLOB SUB_TYPE BINARY`).

**Comment by mrotteveel** [comment]
I'm migrating this to a discussion, as it doesn't seem to be a bug report about Jaybird.

**Comment by mrotteveel** [comment]
Scratch that, I forgot that this repository doesn't have discussions enabled :)
